### ISSUE TITLE
Doesn't work with spaces in path

### ISSUE THREAD

**Issue by Samisafool** [packwiz-gui/packwiz-gui#55]
lol idk why

**Comment by Samisafool** [comment]
Wait no it works wtf

**Comment by ExoPlant** [comment]
Does it work on Windows? This sounds like an issue Windows would have

**Comment by Samisafool** [comment]
Not really sure, it works sometimes but sometimes it doesn't

**Comment by ExoPlant** [comment]
I think we can confirm this fixed

**Comment by Samisafool** [comment]
When was it confirmed?

**Comment by Samisafool** [comment]
> Timeout

I hate you ~~some~~ all of the time.

**Comment by Samisafool** [comment]
STOP. FUCKING. TIMING. ME. OUT.

**Comment by Samisafool** [comment]
IDFC

**Comment by Samisafool** [comment]
GO DIE

**Comment by Samisafool** [comment]
I HATE YOU

**Comment by ExoPlant** [comment]
I hate you too, banned member. Just clearing a few old issues up
